(() => {
'use strict';
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => crypto.randomUUID();
const localKey = 'athlete-personal-trial-v1';
const legacyKey = 'athlete-os-v3';
const blank = () => ({profile:null,sessions:[],goals:[]});
const dateKey = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseDate = s => new Date(`${s}T12:00:00`);
const addDays = (s,n) => {const d=parseDate(s);d.setDate(d.getDate()+n);return dateKey(d)};
const today = () => dateKey(new Date());
const monday = () => {const d=new Date();return addDays(dateKey(d),-((d.getDay()+6)%7))};
const fmt = (s,opts={day:'numeric',month:'long'}) => parseDate(s).toLocaleDateString('fr-FR',opts);
const types = {strength:'Musculation',running:'Course',cycling:'Vélo',mobility:'Mobilité',other:'Autre sport'};
const statuses = {planned:'Prévue',done:'Terminée',skipped:'Non réalisée'};
const icons={week:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/>',sessions:'<path d="M6 5v14M3 8v8M18 5v14M21 8v8M6 12h12"/>',goals:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',account:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>'};
const icon = key => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${icons[key]}</svg>`;
const brand = '<a class="brand" href="./index.html" aria-label="Athlete OS, accueil"><span class="brand-mark">a.</span>athlete os</a>';
let doc=blank(),mode=null,user=null,revision=null,tab='week',week=monday(),busy=false,client=null,noticeTimer,loadFailed=false;
const config=window.ATHLETE_CONFIG || {};
const configured=Boolean(config.supabaseUrl && config.supabasePublishableKey);
if(configured && window.supabase){try{client=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey)}catch{console.error('Configuration de connexion invalide.')}}
function notify(text){$('#notice').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',5500)}
function validDoc(d){return d && typeof d==='object' && Array.isArray(d.sessions) && Array.isArray(d.goals) && (d.profile===null || (typeof d.profile==='object' && typeof d.profile.name==='string'))}
function migrateLegacy(){
 try{
  const raw=localStorage.getItem(legacyKey); if(!raw) return null;
  const old=JSON.parse(raw), start=old?.program?.startDate; if(!start) return null;
  const days=[['Bas A — Force','strength',60],['Haut A — Force','strength',70],['Course 1 — Zone 2','running',40],['Bas B — Unilatéral','strength',60],['Haut B — Volume','strength',65],['Course 2 — Technique','running',35]];
  const sessions=[];
  for(let w=0;w<10;w++) days.forEach((d,i)=>sessions.push({id:uid(),title:d[0],type:d[1],date:addDays(start,w*7+i),duration:d[2],status:'planned',notes:'Séance reprise du Bloc 1 historique.',exercises:[]}));
  const name=old?.athlete?.name || 'Athlète';
  return {profile:{name,focus:'Bloc 1 — Recomposition & base',frequency:6},sessions,goals:[]};
 }catch{return null}
}
async function persist(next){
 if(busy) throw new Error('Un enregistrement est déjà en cours.'); busy=true;
 try {
  if(mode==='local'){try{localStorage.setItem(localKey,JSON.stringify(next))}catch{throw new Error('Le navigateur ne peut pas enregistrer les données. Vérifiez l’espace disponible. Votre saisie est conservée.')}}
  else {
   if(!user || loadFailed) throw new Error('Rechargez votre espace avant de modifier vos données.');
   const values={data:next,revision:(revision ?? 0)+1};
   const query=revision===null ? client.from('athlete_spaces').insert({user_id:user.id,...values}) : client.from('athlete_spaces').update(values).eq('user_id',user.id).eq('revision',revision);
   const {data,error}=await query.select('revision').single();
   if(error) throw new Error('Enregistrement impossible : connexion interrompue ou données modifiées sur un autre appareil. Votre saisie reste ouverte. Rechargez avant de réessayer.');
   revision=data.revision;
  }
  doc=next;
 } finally {busy=false}
}
function close(){ $('#editor').close(); $('#editor').innerHTML=''; }
function modal(title,body){const d=$('#editor');d.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button type="button" data-action="close" aria-label="Fermer">×</button></div>${body}`;if(!d.open)d.showModal();}
function welcome(){
 $('#app').innerHTML=`<main class="welcome" id="main"><header>${brand}</header><div class="welcome-main"><section><p class="tag">Votre sport. Votre rythme.</p><h1 style="margin-top:20px">Une semaine qui vous ressemble.</h1><p class="lead">Planifiez vos séances, notez vos résultats et avancez vers vos objectifs. Tout votre entraînement, au même endroit.</p><div class="row"><button class="primary" data-action="auth">Créer mon compte</button><button class="quiet" data-action="auth">Me connecter</button></div><p style="margin-top:18px"><button class="quiet" data-action="trial">Essayer sur cet appareil →</button></p><p class="field-help" style="margin-top:12px">L’essai reste dans ce navigateur. Un compte permet de retrouver son suivi sur plusieurs appareils.</p></section><aside class="panel preview" aria-label="Exemple de semaine, données illustratives"><div class="row between"><h2>Une semaine à votre rythme</h2><span class="tag">Exemple</span></div><div class="preview-days"><span>Lun<br>12</span><span class="selected">Mar<br>13</span><span>Mer<br>14</span><span>Jeu<br>15</span><span>Ven<br>16</span><span>Sam<br>17</span><span>Dim<br>18</span></div><div class="preview-item"><span class="symbol">✓</span><div><b>Haut du corps</b><p>45 min · Séance terminée</p></div></div><div class="preview-item"><span class="symbol">↗</span><div><b>Course à pied</b><p>30 min · Prochaine séance</p></div></div><div class="preview-item"><span class="symbol">○</span><div><b>Du temps pour récupérer</b><p>Vous choisissez les jours de repos.</p></div></div></aside></div><footer class="welcome-foot"><span>Un espace personnel pour chaque athlète.</span><a href="./legacy.html">Accéder à mon suivi historique</a></footer></main>`;
}
function render(){
 if(!mode){welcome();return}
 const nav=[['week','Ma semaine'],['sessions','Mes séances'],['goals','Mes objectifs'],['account','Mon compte']];
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar">${brand}<nav class="nav" aria-label="Navigation principale">${nav.map(([key,label])=>`<button data-tab="${key}" class="${tab===key?'active':''}" ${tab===key?'aria-current="page"':''}>${icon(key)}${label}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="identity"><span class="avatar">${esc((doc.profile?.name || 'A').slice(0,1).toUpperCase())}</span><div>${esc(doc.profile?.name || 'Mon espace')}<br><small>${mode==='local'?'Essai sur cet appareil':'Compte personnel'}</small></div></div><a href="./legacy.html">Mon suivi historique ↗</a></div></aside><main class="workspace" id="main"><div class="topline"><span>MON ENTRAÎNEMENT</span><span><span class="status-dot"></span>${mode==='local'?'Enregistré dans ce navigateur':'Espace personnel connecté'}</span></div>${loadFailed?`<section class="panel empty"><h1>Espace indisponible</h1><p>Impossible de charger votre suivi. Aucune donnée n’a été remplacée.</p><button data-action="reload" class="primary">Réessayer</button><button data-action="logout">Se déconnecter</button></section>`:!doc.profile?onboarding():tab==='week'?weekPage():tab==='sessions'?sessionsPage():tab==='goals'?goalsPage():accountPage()}</main></div>`;
}
function onboarding(){return `<section class="onboarding"><p class="tag">Bienvenue dans votre espace</p><h1>Commençons par vous.</h1><p class="muted">Quelques repères pour organiser votre semaine. Vous pourrez les modifier à tout moment.</p>${profileForm(true)}</section>`}
function profileForm(first=false){const p=doc.profile || {name:'',frequency:3,focus:'Prendre une habitude régulière'};return `<form id="profile-form" class="form-stack"><label>Prénom<input name="name" autocomplete="given-name" maxlength="60" value="${esc(p.name)}" required></label><label>Votre priorité<input name="focus" maxlength="160" placeholder="Ex. courir régulièrement, gagner en force…" value="${esc(p.focus)}" required></label><label>Nombre de séances visées par semaine<input name="frequency" type="number" min="1" max="14" value="${esc(p.frequency)}" required></label><p class="field-help">C’est votre rythme souhaité, pas une prescription d’entraînement.</p><p class="error" role="alert"></p><button class="primary">${first?'Créer ma semaine':'Enregistrer mon profil'}</button></form>`}
function heading(title,copy,action,label){return `<header class="page-head"><div><h1>${title}</h1><p>${copy}</p></div>${action?`<button class="primary" data-action="${action}">+ ${label}</button>`:''}</header>`}
function weekPage(){
 const days=Array.from({length:7},(_,i)=>addDays(week,i)),list=doc.sessions.filter(s=>days.includes(s.date)),done=list.filter(s=>s.status==='done').length,target=doc.profile.frequency;
 const next=doc.sessions.filter(s=>s.date>=today() && s.status==='planned').sort((a,b)=>a.date.localeCompare(b.date))[0];
 return `${heading('Ma semaine',`Bonjour ${esc(doc.profile.name)}. Faites de la place à ce qui vous fait avancer.`,'new-session','Planifier une séance')}<div class="week-toolbar"><h2>${fmt(week)} — ${fmt(days[6],{day:'numeric',month:'long',year:'numeric'})}</h2><div class="week-nav"><button data-action="prev-week" aria-label="Semaine précédente">←</button><button data-action="this-week">Cette semaine</button><button data-action="next-week" aria-label="Semaine suivante">→</button></div></div><div class="week-grid">${days.map(date=>{const sessions=list.filter(s=>s.date===date);return `<section class="day ${date===today()?'today':''}" aria-label="${fmt(date,{weekday:'long',day:'numeric',month:'long'})}"><div class="day-head"><span>${fmt(date,{weekday:'short'})}</span><span class="day-number">${parseDate(date).getDate()}</span></div><div class="day-sessions">${sessions.length?sessions.map(s=>`<button class="session ${s.status} ${s.type}" data-session="${esc(s.id)}"><span class="tag">${esc(types[s.type] || 'Sport')}</span><strong>${esc(s.title)}</strong><small>${s.duration} min · ${statuses[s.status] || 'Prévue'}</small></button>`).join(''):'<p class="rest">Libre / repos</p>'}</div><button class="add-day" data-date="${date}" aria-label="Ajouter une séance le ${fmt(date)}">+ Ajouter</button></section>`}).join('')}</div><div class="summary-grid"><section class="panel"><div class="row between"><h2>Votre rythme</h2><span class="tag">${done} / ${target} séances</span></div><div class="progress" role="progressbar" aria-label="Séances terminées par rapport à votre rythme souhaité" aria-valuenow="${Math.min(done,target)}" aria-valuemin="0" aria-valuemax="${target}"><span style="width:${Math.min(100,done/target*100)}%"></span></div><p class="muted">${done} terminée${done>1?'s':''} · ${list.filter(s=>s.status==='planned').length} prévue${list.filter(s=>s.status==='planned').length>1?'s':''} cette semaine</p><div class="next"><p class="tag">Prochaine séance à venir</p>${next?`<div class="row between" style="margin-top:10px"><div><h3>${esc(next.title)}</h3><small>${fmt(next.date)} · ${next.duration} min</small></div><button data-session="${esc(next.id)}">Ouvrir →</button></div>`:'<p class="muted" style="margin-top:8px">Choisissez un jour pour votre prochaine séance.</p>'}</div></section><section class="panel"><p class="tag">Votre priorité</p><h2 style="margin-top:14px">${esc(doc.profile.focus)}</h2><p class="muted" style="margin:15px 0 22px">${doc.goals.length?`${doc.goals.length} objectif${doc.goals.length>1?'s':''} à suivre à votre rythme.`:'Ajoutez une cible mesurable pour voir votre progression.'}</p><button data-tab="goals">Voir mes objectifs →</button></section></div>`;
}
function sessionsPage(){const list=[...doc.sessions].sort((a,b)=>b.date.localeCompare(a.date));return `${heading('Mes séances','Planifiez, retrouvez vos résultats et réutilisez vos séances.','new-session','Créer une séance')}<div class="list">${list.length?list.map(s=>`<article class="panel session-row"><div class="date-tile">${fmt(s.date,{month:'short'})}<strong>${parseDate(s.date).getDate()}</strong></div><div class="session-body"><span class="tag">${esc(types[s.type])} · ${statuses[s.status]}</span><h3>${esc(s.title)}</h3><p>${fmt(s.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'})} · ${s.duration} min · ${s.exercises.length} exercice${s.exercises.length>1?'s':''}</p></div><button data-session="${esc(s.id)}">${s.status==='done'?'Voir les résultats':'Ouvrir la séance'} →</button></article>`).join(''):`<section class="panel empty"><h2>Votre première séance commence ici.</h2><p>Donnez-lui un nom, choisissez un jour et ajoutez vos exercices. Vous pourrez noter vos résultats après l’entraînement.</p><button class="primary" data-action="new-session">Créer ma première séance</button></section>`}</div>`}
function goalsPage(){return `${heading('Mes objectifs','Des cibles qui vous appartiennent. Une progression visible.','new-goal','Ajouter un objectif')}<div class="goal-list">${doc.goals.length?doc.goals.map(g=>{const pct=Math.max(0,Math.min(100,((g.current-g.start)/(g.target-g.start))*100));return `<article class="panel"><div class="row between"><h2>${esc(g.title)}</h2><button data-goal="${esc(g.id)}">Mettre à jour</button></div><div class="progress"><span style="width:${pct}%"></span></div><p>${g.current} / ${g.target} ${esc(g.unit)} <span class="muted">· ${Math.round(pct)} % du chemin</span></p><p class="goal-meta">Départ : ${g.start} ${esc(g.unit)}${g.deadline?` · Échéance : ${fmt(g.deadline,{day:'numeric',month:'long',year:'numeric'})}`:''}</p></article>`}).join(''):`<section class="panel empty"><h2>Qu’aimeriez-vous accomplir ?</h2><p>Une distance, un nombre de séances, une charge : choisissez une mesure concrète et votre point de départ.</p><button class="primary" data-action="new-goal">Définir mon premier objectif</button></section>`}</div>`}
function accountPage(){return `${heading('Mon compte','Votre profil, vos données et votre connexion.')}<div class="account-grid"><section class="panel"><h2 style="margin-bottom:22px">Mon profil</h2>${profileForm()}</section><section class="panel"><h2>${mode==='local'?'Essai sur cet appareil':'Mon espace privé'}</h2><p class="muted" style="margin-top:12px">${mode==='local'?'Vos séances restent dans ce navigateur. Cet essai n’est pas un compte et ne se synchronise pas.':esc(user.email)}</p><div class="row">${mode==='local'?'<button class="primary" data-action="auth">Créer mon compte / Me connecter</button>':''}<button data-action="export">Exporter mes données</button><button data-action="logout">${mode==='local'?'Quitter l’essai':'Se déconnecter'}</button></div>${mode==='cloud'?'<p class="field-help" style="margin-top:14px">Les données de votre compte sont chargées à la connexion. Elles ne sont pas conservées dans le stockage local de l’essai.</p>':''}</section><section class="panel"><h2>Mon suivi historique</h2><p class="muted" style="margin:12px 0">Votre ancien programme, vos imports et votre historique restent accessibles dans l’application d’origine. Ils ne sont pas transférés automatiquement.</p><a href="./legacy.html">Ouvrir mon suivi historique →</a></section></div>`}
function exerciseRow(e={name:'',sets:3,reps:10,load:''}){return `<div class="exercise"><div class="exercise-top"><label>Exercice<input name="exercise-name" maxlength="120" value="${esc(e.name)}" placeholder="Ex. squat, rameur…" required></label><button type="button" data-action="remove-exercise" aria-label="Supprimer cet exercice">×</button></div><div class="exercise-values"><label>Séries<input name="sets" type="number" min="1" max="100" value="${esc(e.sets)}" required></label><label>Répétitions<input name="reps" type="number" min="1" max="1000" value="${esc(e.reps)}" required></label><label>Charge (kg)<input name="load" type="number" min="0" max="2000" step="0.1" value="${esc(e.load)}" placeholder="Facultatif"></label></div></div>`}
function sessionEditor(id,date){const s=doc.sessions.find(x=>x.id===id) || {id:'',title:'',type:'strength',date:date || today(),duration:45,status:'planned',exercises:[],notes:''};modal(s.id?'Ma séance':'Nouvelle séance',`<form id="session-form" data-id="${esc(s.id)}" class="form-stack"><label>Nom de la séance<input name="title" maxlength="100" value="${esc(s.title)}" placeholder="Ex. haut du corps, footing du dimanche…" required></label><div class="form-grid"><label>Sport<select name="type">${Object.entries(types).map(([k,v])=>`<option value="${k}" ${s.type===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Date<input name="date" type="date" value="${s.date}" required></label><label>Durée (minutes)<input name="duration" type="number" min="1" max="1440" value="${s.duration}" required></label><label>État<select name="status">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${s.status===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div><h3>Exercices & résultats</h3><p class="field-help" style="margin:8px 0 14px">Préparez vos séries, puis ajustez-les à ce que vous avez réalisé. Pour la course, précisez distance et allure dans les notes.</p><div id="exercises" class="list">${s.exercises.map(exerciseRow).join('')}</div><button type="button" data-action="add-exercise" style="margin-top:12px">+ Ajouter un exercice</button></div><label>Notes de séance<textarea name="notes" maxlength="4000" placeholder="Distance, allure, ressenti, détail des séries…">${esc(s.notes)}</textarea></label><p class="error" role="alert"></p><div class="row between">${s.id?`<button type="button" data-duplicate="${esc(s.id)}">Dupliquer</button><button type="button" class="quiet danger" data-delete-session="${esc(s.id)}">Supprimer</button>`:''}</div><div class="dialog-actions"><button type="button" data-action="close">Annuler</button><button class="primary">Enregistrer la séance</button></div></form>`)}
function goalEditor(id){const g=doc.goals.find(x=>x.id===id) || {id:'',title:'',start:0,current:0,target:'',unit:'',deadline:''};modal(g.id?'Mon objectif':'Nouvel objectif',`<form id="goal-form" data-id="${esc(g.id)}" class="form-stack"><label>Objectif<input name="title" maxlength="120" value="${esc(g.title)}" placeholder="Ex. courir 10 km sans m’arrêter" required></label><div class="form-grid"><label>Valeur de départ<input name="start" type="number" step="any" value="${g.start}" required></label><label>Valeur actuelle<input name="current" type="number" step="any" value="${g.current}" required></label><label>Cible<input name="target" type="number" step="any" value="${g.target}" required></label><label>Unité<input name="unit" maxlength="30" value="${esc(g.unit)}" placeholder="km, séances, kg…" required></label></div><label>Échéance (facultative)<input name="deadline" type="date" value="${g.deadline}"></label><p class="field-help">La progression fonctionne pour une cible à la hausse comme à la baisse.</p><p class="error" role="alert"></p><div class="dialog-actions">${g.id?`<button type="button" class="danger quiet" data-delete-goal="${esc(g.id)}">Supprimer</button>`:''}<button class="primary">Enregistrer l’objectif</button></div></form>`)}
function auth(){if(!client){modal('Les comptes arrivent bientôt',`<p>La connexion n’est pas encore activée sur cette version. Vous pouvez déjà créer vos séances dans un essai enregistré sur cet appareil.</p><div class="dialog-actions"><button class="primary" data-action="trial">Essayer sur cet appareil</button></div>`);return}modal('Votre espace personnel',`<p class="muted" style="margin-bottom:22px">Nouveau ou déjà inscrit : recevez un lien de connexion par e-mail. Aucun mot de passe à retenir.</p><form id="auth-form" class="form-stack"><label>Adresse e-mail<input name="email" type="email" autocomplete="email" required></label><p class="field-help">Votre espace sera créé après confirmation de votre adresse. Les données d’essai ne sont pas transférées automatiquement.</p><p class="error" role="alert"></p><button class="primary">Recevoir mon lien de connexion</button></form>`)}
async function loadCloud(){const owner=user?.id;if(!owner)return;mode='cloud';doc=blank();revision=null;loadFailed=false;$('#app').innerHTML='<p class="loading">Chargement de votre espace personnel…</p>';try{const {data,error}=await client.from('athlete_spaces').select('data,revision').eq('user_id',owner).maybeSingle();if(user?.id!==owner || mode!=='cloud')return;if(error)throw error;if(data){if(!validDoc(data.data))throw new Error('Format de données non reconnu');doc=data.data;revision=data.revision}}catch{if(user?.id!==owner || mode!=='cloud')return;loadFailed=true}render()}
async function trial(){close();try{const raw=localStorage.getItem(localKey);let stored=raw?JSON.parse(raw):null;const legacy=migrateLegacy();let imported=false;if(!stored){stored=legacy;imported=Boolean(legacy)}else if(validDoc(stored) && stored.sessions.length===0 && legacy?.sessions.length){stored={...stored,profile:stored.profile||legacy.profile,sessions:legacy.sessions};imported=true}if(imported)localStorage.setItem(localKey,JSON.stringify(stored));stored=stored||blank();if(!validDoc(stored))throw new Error();doc=stored;mode='local';user=null;revision=null;loadFailed=false;render();if(imported)notify('Votre planning historique a été repris dans Ma semaine.')}catch{notify('Impossible de lire votre essai. Les données existantes ont été conservées.')}}
document.addEventListener('click',async event=>{
 const b=event.target.closest('button');if(!b || busy)return;
 try{
 if(b.dataset.tab){tab=b.dataset.tab;render();return}
 if(b.dataset.session){sessionEditor(b.dataset.session);return}
 if(b.dataset.date){sessionEditor(null,b.dataset.date);return}
 if(b.dataset.goal){goalEditor(b.dataset.goal);return}
 if(b.dataset.duplicate){const s=doc.sessions.find(x=>x.id===b.dataset.duplicate);sessionEditor();const f=$('#session-form');f.elements.title.value=s.title+' (copie)';f.elements.type.value=s.type;f.elements.duration.value=s.duration;f.elements.notes.value=s.notes;$('#exercises').innerHTML=s.exercises.map(exerciseRow).join('');return}
 if(b.dataset.deleteSession || b.dataset.deleteGoal){const isSession=!!b.dataset.deleteSession,id=b.dataset.deleteSession || b.dataset.deleteGoal;if(!window.confirm(isSession?'Supprimer cette séance et ses résultats ?':'Supprimer cet objectif ?'))return;const next=structuredClone(doc),key=isSession?'sessions':'goals';next[key]=next[key].filter(x=>x.id!==id);await persist(next);close();render();notify('Suppression enregistrée.');return}
 switch(b.dataset.action){
 case 'close':close();break;
 case 'auth':auth();break;
 case 'trial':await trial();break;
 case 'new-session':sessionEditor(null,week===monday()?today():week);break;
 case 'new-goal':goalEditor();break;
 case 'prev-week':week=addDays(week,-7);render();break;
 case 'next-week':week=addDays(week,7);render();break;
 case 'this-week':week=monday();render();break;
 case 'add-exercise':$('#exercises').insertAdjacentHTML('beforeend',exerciseRow());$('#exercises').lastElementChild.querySelector('input').focus();break;
 case 'remove-exercise':b.closest('.exercise').remove();break;
 case 'reload':await loadCloud();break;
 case 'export':{const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`athlete-os-personnel-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break}
 case 'logout':if(mode==='cloud'){const {error}=await client.auth.signOut();if(error)throw new Error('Déconnexion impossible. Réessayez.')}mode=null;user=null;doc=blank();revision=null;close();render();break;
 }
 }catch(error){const err=$('#editor[open] .error');if(err)err.textContent=error.message;else notify(error.message)}
});
document.addEventListener('submit',async event=>{
 const f=event.target;if(!['profile-form','session-form','goal-form','auth-form'].includes(f.id))return;event.preventDefault();if(busy)return;
 const error=f.querySelector('.error');error.textContent='';const button=f.querySelector('button.primary');button.disabled=true;
 try{
 const data=new FormData(f),next=structuredClone(doc);
 if(f.id==='auth-form'){const {error:err}=await client.auth.signInWithOtp({email:String(data.get('email')).trim(),options:{emailRedirectTo:new URL('./index.html',location.href).href}});if(err)throw new Error('Le lien n’a pas pu être envoyé. Vérifiez l’adresse ou réessayez dans quelques instants.');modal('Consultez votre messagerie',`<p>Si l’adresse est autorisée, un lien de connexion vous a été envoyé. Ouvrez-le pour accéder à votre espace.</p><p class="muted" style="margin-top:14px">Pensez à vérifier les courriers indésirables.</p>`);return}
 if(f.id==='profile-form'){next.profile={name:String(data.get('name')).trim(),focus:String(data.get('focus')).trim(),frequency:Number(data.get('frequency'))};if(!next.profile.name || !next.profile.focus)throw new Error('Renseignez votre prénom et votre priorité.');}
 if(f.id==='session-form'){const s={id:f.dataset.id || uid(),title:String(data.get('title')).trim(),type:data.get('type'),date:data.get('date'),duration:Number(data.get('duration')),status:data.get('status'),notes:String(data.get('notes')).trim(),exercises:[...f.querySelectorAll('.exercise')].map(row=>({name:row.querySelector('[name="exercise-name"]').value.trim(),sets:Number(row.querySelector('[name="sets"]').value),reps:Number(row.querySelector('[name="reps"]').value),load:row.querySelector('[name="load"]').value}))};if(!s.title || s.exercises.some(e=>!e.name))throw new Error('Donnez un nom à la séance et à chaque exercice.');next.sessions=next.sessions.filter(x=>x.id!==s.id).concat(s);}
 if(f.id==='goal-form'){const g={id:f.dataset.id || uid(),title:String(data.get('title')).trim(),start:Number(data.get('start')),current:Number(data.get('current')),target:Number(data.get('target')),unit:String(data.get('unit')).trim(),deadline:data.get('deadline')};if(g.start===g.target)throw new Error('La cible doit être différente de votre point de départ.');if(!g.title || !g.unit)throw new Error('Renseignez un titre et une unité.');next.goals=next.goals.filter(x=>x.id!==g.id).concat(g);}
 await persist(next);close();render();notify('Enregistré.');
 }catch(err){error.textContent=err.message || 'Enregistrement impossible. Votre saisie est conservée.'}finally{button.disabled=false}
});
async function init(){if(client){try{const {data,error}=await client.auth.getSession();if(error)throw error;if(data.session){user=data.session.user;await loadCloud()}else render();client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT' && mode==='cloud'){close();mode=null;user=null;doc=blank();revision=null;render()}if(event==='SIGNED_IN' && session && session.user.id!==user?.id){user=session.user;close();setTimeout(loadCloud,0)}})}catch{render();notify('Connexion indisponible. Réessayez plus tard.')}}else render();if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
init();
})();
